export default {
    Card: {
        ID: 'Unique card identifier.',
        LUID: 'Card locally unique identifier, commonly combined with the project LUID.',
        Caption: 'Primary display name or title of the card.',
        CardType: 'Card type defining the card workflow, behavior, and custom fields.',
        Project: 'Project to which the card belongs.',
        Task: 'Work-package task to which the card belongs.',
        ParentCard: 'Parent card when this card is part of a card hierarchy.',
        SortOrder: 'Display order of the card within its context.',
        Domain: 'Optional business domain or category used to group cards.',
        IsClosed: 'Whether the card is closed or completed.',
        ClosedWhen: 'Date and time when the card was closed. Null while the card remains open.',
        CreatedWhen: 'Date and time when the card was created.',
        CreatedBy: 'User who created the card.',
        ChangedWhen: 'Date and time of the most recent card change.',
        ChangedBy: 'User who most recently changed the card.',
        LockedWhen: 'Date and time when the card was locked. Null when it is not locked.',
        HasPredecessors: 'Whether predecessor relationships have been defined for the card.',
        ExternalKey: 'Identifier of the corresponding item in an external system.',
        ExternalType: 'Type or name of the external system, for example Jira.',
        ExternalProjectKey: 'Project identifier used by the external system.',
        KanbanTokenRequired: 'Whether working on the card requires a Kanban token. Derived from KanbanTokensRequired.',
        KanbanTokensRequired: 'Number of Kanban tokens consumed by the card for work-in-progress limits.',
        ActiveStatusSetWhen: 'Date and time when the card entered its current active status.',
        ActiveHoursBeforeToday: 'Accumulated active working time before the current day.',
        ActiveHoursToday: 'Active working time recorded for the current day.',
        ActiveHoursTodayDate: 'Date to which ActiveHoursToday applies.',
        TimeSpent: 'Total calculated working time spent on the card.',
        EttcRemaining: 'Estimated time remaining to complete the card.',
        BufferTokenRequired: 'Whether the card requires a buffer-management token.',
        BufferPercentage: 'Current buffer consumption. Negative values are ahead of schedule, 0.0 to 1.0 consume the buffer, and values above 1.0 exceed it.',
        BufferZone: 'Drum-buffer-rope zone: -1 not applicable, 0 ahead, 1 green, 2 orange, 3 red, or 5 black.',
        ShowBufferPercentageAsZeroPct: 'Whether a slightly negative buffer percentage should be displayed as 0% in the green zone.',
        CauseOfDelay: 'Recorded cause-of-delay information. Null when no delay has been reported.'
    },
    CauseOfDelay: {
        BufferConsumed: 'Buffer consumption at the time the delay was reported.',
        Causes: 'Reported causes of the delay.',
        Trigger: 'Event or reason that triggered delay reporting.',
        Comment: 'Additional explanation of the delay.',
        When: 'Date and time when the delay was reported.',
        ReportedBy: 'User who reported the delay.'
    }
};
